### ISSUE TITLE
Incorrect axis ticks/scale in spectrogram's frequency scale (correct value / 2)

### ISSUE THREAD

**Issue by pklaus** [flothesof/pyqtgraph-spectrographer#3]
I realized that the frequency scale in the spectrogram view is off by a factor of 0.5.

Great work on the pyqtgraph based spectrogram! I love it!

**Comment by flothesof** [comment]
Thanks for reporting this!
I'll fix it when I next work on the spzxtrographer. I'm happy you like it!

**Comment by flothesof** [comment]
I corrected the axis of the waterfall plot.

Thanks for reporting the issue (I hadn't thought of verifying with real sounds if the axis was right, I should have...)
